### ISSUE TITLE
Rendering Crash when opening a jei tab related to immersive weapons

### ISSUE THREAD

**Issue by border999** [AnonymousHacker1279/IWCompatibilityBridge#6]
[crash-2023-03-16_20.59.45-client.txt](https://github.com/AnonymousHacker1279/IWCompatibilityBridge/files/10996918/crash-2023-03-16_20.59.45-client.txt)

**Comment by AnonymousHacker1279** [comment]
The 1.18.2 version was built against JEI 9.5.5.174, and you are using a newer version (10.x.x.x) which includes breaking changes, causing IWCB to crash. I no longer support 1.18.2, so you will need to downgrade JEI or not include IWCB.
